import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Menu from './Menu'
import Hero from './Hero'
import Text_separator from './Text_separator'
import Temporaire from './Temporaire'
import About from './About'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Minh Thanh - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Menu/>
        <Hero/>
        <Text_separator/>
        <About/>
        <Temporaire/>
      </main>

      <footer>
        footer
      </footer>
    </div>
  )
}
