import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Menu from './Menu'
import Hero from './Hero'
import Text_separator from './Text_separator'
import About from './About'
import Works from './Works'
import Contact from './Contact'
import Footer from './Footer'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Minh Thanh - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <main className={styles.main}>
        <Hero />
        <Text_separator />
        <About />
        <Works />
        <Contact />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  )
}